import { type NextPage } from "next";
import Head from "next/head";
import { useId } from "react";
import NoSSR from "react-no-ssr";
import { useAccount, useContractRead } from "wagmi";
import { marketAbi, marketAddress, nftAbi, nftAddress } from "~/contracts/NFT";

const Home: NextPage = () => {
  const account = useAccount();

  const myMarketplaceNFTs = useContractRead({
    abi: marketAbi,
    address: marketAddress,
    functionName: "fetchMyNFTs",
  });

  const balanceOf = useContractRead({
    abi: nftAbi,
    address: nftAddress,
    functionName: "balanceOf",
    // @ts-expect-error wagmi address type
    args: [account.address],
  });

  return (
    <>
      <Head>
        <title>Openseal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <NoSSR>
          <div className="flex w-full flex-col gap-12 px-4 py-16">
            <h1>My Overview</h1>
            {account.status === "disconnected" && <div>Not connected...</div>}
            {account.status === "connected" && (
              <div className="grid grid-cols-2 gap-4">
                {balanceOf.data && (
                  <div>
                    <h2>My NFTs</h2>
                    <div className="">
                      Owned ERC721 Tokens: {balanceOf.data.toNumber()}
                    </div>
                  </div>
                )}
                {myMarketplaceNFTs.error && (
                  <div>{myMarketplaceNFTs.error.message}</div>
                )}
                {myMarketplaceNFTs.data?.length === 0 && (
                  <div>You have no NFTs on the marketplace yet.</div>
                )}
                {(myMarketplaceNFTs.data?.length || 0) > 0 && (
                  <div>
                    <h2>My Marketplace NFTs</h2>
                    <div className="flex flex-col gap-4">
                      {myMarketplaceNFTs.data?.length}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </NoSSR>
      </main>
    </>
  );
};

export default Home;
